franchises/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls import url
from .views import *

urlpatterns = [
    path("plan-management/", plan_management, name="plan_management"),
    path("plan-management/<int:plan_id>", plan_management, name="plan_management"),
    path("list", franchise_list, name="franchise_list"),
    url(
        r"^registrar-solicitud/(?P<plan_id>\d+)$",
        register_franchise,
        name="franchise_register_franchise",
    ),
    url(
        r"^registrar-solicitud", register_franchise, name="franchise_register_franchise"
    ),
    url(
        r"^copia-seguridad/(?P<franchise_id>\d+)$",
        dump_data,
        name="franchise_backup_franchise",
    ),
]

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls import url
from .views import *

from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("register-user-admin/", register_user_admin, name="register_user_admin"),
    path("dashboard/", dashboard, name="dashboard"),
    path(
        "login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
    path("profile/", user_profile, name="user_profile"),
    url(r"^list", UsersList.as_view(), name="users_list"),
    path("clients_list/", clients_list, name="clients_list"),
]

SuperPizzas/franchises/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django_tenants.models import DomainMixin, TenantMixin
from django_tenants.postgresql_backend.base import _is_valid_schema_name

from django.conf import settings


class Module(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Plan(models.Model):
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField()
    modules = models.ManyToManyField(Module)
    max_users = models.PositiveIntegerField()

    def __str__(self):
        return self.name

    def get_avalaible_modules(self):
        return [str(module) for module in self.modules.all()]


def check_schema_name(name):
    if not _is_valid_schema_name(name):
        raise ValidationError("El nombre del esquema es inválido.")


class Franchise(TenantMixin):
    name = models.CharField("Nombre de la franquicia", max_length=300, unique=True)
    schema_name = models.CharField(
        max_length=300, unique=True, validators=[check_schema_name]
    )
    client = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name="Cliente de la franquicia",
        related_name="franchises",
        on_delete=models.SET_NULL,
        null=True
    )
    plan = models.ForeignKey(Plan, related_name="franchises", on_delete=models.SET_NULL, null=True)
    validity = models.DateTimeField(
        help_text="Fecha hasta la que se encuentra pago el servicio"
    )

    def __str__(self):
        return self.name


class Domain(DomainMixin):
    pass

franchises/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django_tenants.models import DomainMixin, TenantMixin
from django_tenants.postgresql_backend.base import _is_valid_schema_name

from simple_history.models import HistoricalRecords
from django.conf import settings

from users.models import User


class Module(models.Model):
    name = models.CharField(max_length=100)

    @staticmethod
    def initial_modules():
        Module.objects.get_or_create(name="Usuarios")
        Module.objects.get_or_create(name="Pizzas")

    def __str__(self):
        return self.name


class Plan(models.Model):
    @staticmethod
    def search(id):
        try:
            return Franchise.objects.get(id=id)
        except Franchise.DoesNotExist:
            return None



    name = models.CharField(max_length=100, verbose_name="nombre")
    description = models.CharField(
        max_length=1000, verbose_name="descripción", blank=True, null=True
    )
    price = models.PositiveIntegerField(verbose_name="precio")
    modules = models.ManyToManyField(Module, verbose_name="modulos")
    max_users = models.PositiveIntegerField(verbose_name="máximo de usuarios")

    class Meta:
        ordering = ["price"]

    def __str__(self):
        return self.name

    @staticmethod
    def search(id):
        try:
            return Plan.objects.get(id=id)
        except Plan.DoesNotExist:
            return None

    def get_avalaible_modules(self):
        return [str(module) for module in self.modules.all()]


def check_schema_name(name):
    if not _is_valid_schema_name(name):
        raise ValidationError("El nombre del esquema es inválido.")


class Franchise(TenantMixin):
    THEME_TYPE = (
        ("a", "Tema A"),
        ("b", "Tema B"),
        ("c", "Tema C"),
        ("d", "Tema D"),
        ("e", "Tema E"),
    )
    THEME_COLOR = (
        ("coffee", "Café"),
        ("dark", "Oscuro"),
        ("dust", "Arena"),
        ("gray", "Gris"),
        ("lime", "Lima"),
        ("mint", "Menta"),
        ("navy", "Azul marino"),
        ("ocean", "Oceano"),
        ("prickly-pear", "Higo"),
        ("purple", "Violeta"),
        ("well-red", "Rojo"),
        ("yellow", "Amarillo"),
    )

    name = models.CharField("Nombre de la franquicia", max_length=300, unique=True)
    schema_name = models.CharField(
        "Subdominio", max_length=300, unique=True, validators=[check_schema_name]
    )
    client = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name="Cliente de la franquicia",
        related_name="franchises",
        on_delete=models.SET_NULL,
        null=True,
    )
    plan = models.ForeignKey(
        Plan,
        related_name="franchises",
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Plan",
    )
    theme = models.CharField(
        "Tema", max_length=50, choices=THEME_TYPE, null=False, blank=False, default="a"
    )
    color = models.CharField(
        "Tema",
        max_length=50,
        choices=THEME_COLOR,
        null=False,
        blank=False,
        default="well-red",
    )
    validity = models.DateTimeField(
        "Fecha de vencimiento del servicio",
        help_text="Fecha hasta la que se encuentra pago el servicio",
    )

    def __str__(self):
        return self.name

    @classmethod
    def initial_franchise(cls):
        client = User.initial_user()
        Module.initial_modules()
        if not Franchise.objects.count():
            franchise = Franchise.objects.create(
                name="public", schema_name="public", validity="2099-12-31"
            )
            dominio = Domain.objects.create(
                tenant=franchise, is_primary=True, domain=settings.DOMAIN
            )

            print("Franquicia inicial creada correctamente")
        else:
            print("Ya existe una franquicia")

    def is_available(self):
        return self.validity >= timezone.now()

    @staticmethod
    def search(id):
        try:
            return Franchise.objects.get(id=id)
        except Franchise.DoesNotExist:
            return None


class Domain(DomainMixin):
    history = HistoricalRecords()

    def __str__(self):
        return self.domain

franchises/forms.py
from django import forms
from django_select2.forms import Select2MultipleWidget



from .models import *


class FranchiseForm(forms.ModelForm):

    #,public_key='6Lc68b8UAAAAAClNVCXOXe3iedRGpkaOt_dyOIC-',
    #private_key='6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe')
    def __init__(self, *args, **kwargs):
        from django.conf import settings

        super(FranchiseForm, self).__init__(*args, **kwargs)
        self.fields["schema_name"].label = "Subdominio"
        self.fields[
            "schema_name"
        ].help_text = f"Esta será su dirección: subdominio.{settings.DOMAIN}"
        # self.fields["client"].queryset = self.fields["client"]\
        #    .queryset.filter(position="Client")

    class Meta:
        model = Franchise
        fields = ("name", "schema_name", "validity")
        widgets = {
            "validity": forms.DateInput(
                attrs={"class": "component-date"}, format="%Y-%m-%d"
            )
        }

    def clean(self):
        form_data = self.cleaned_data
        tenant_address = form_data["schema_name"]
        if tenant_address.lower() == "www":
            self._errors["schema_name"] = [
                f"No es posible registrar {tenant_address} como dirección de correo válida"
            ]
        try:
            Franchise.objects.get(schema_name=tenant_address)
            self._errors["schema_name"] = [
                f"Ya existe una franquicia con el nombre {tenant_address}"
            ]
        except:
            pass

        franchise_name = form_data["name"]
        try:
            Franchise.objects.get(name=franchise_name)
            self._errors["nombre"] = [
                f"Ya existe una franquicia con el nombre {tenant_address}"
            ]
        except:
            pass


class ThemeForm(forms.ModelForm):
    class Meta:
        model = Franchise
        fields = ("theme", "color")


class PlanForm(forms.ModelForm):
    class Meta:
        model = Plan
        fields = ("name", "description", "price", "modules", "max_users")
        widgets = {"modules": Select2MultipleWidget()}

franchises/views.py
from django.contrib import messages
from django.db import connection
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect

from SuperPizzas.utils import verify_position
from users.forms import SignUpForm
from users.views import signup
from .forms import *
from .models import *
import sys
from utils.decorators import auth_check_msg

from django.core.management import call_command




def plan_management(request, plan_id=None):
    if plan_id:
        plan = get_object_or_404(Plan, id=plan_id)
    else:
        plan = None
    Module.initial_modules()
    form = PlanForm(instance=plan)

    if request.method == "POST":
        form = PlanForm(request.POST, instance=plan)
        if form.is_valid():
            form.save()
            messages.success(request, "Plan guardado correctamente")
            form = PlanForm()
        else:
            messages.error(request, "Por favor revise los campos en rojo")

    return render(
        request,
        "franchises/plan_management.html",
        {"form": form, "plans": Plan.objects.all()},
    )


#@verify_position(allowed_positions=[User.FRANCHISE])
def register_franchise(request, plan_id=1):
    plan = Plan.search(plan_id)
    if not plan:
        messages.error(request, "No existe el plan buscado")
        return redirect("home")

    if request.method == "POST":
        form_franchise = FranchiseForm(request.POST)
        form_user = SignUpForm(request.POST)
        if form_franchise.is_valid() and form_user.is_valid():

            from django.db import connection
            try:
                user, user_response = signup(request,user_type='admin')
                franchise = form_franchise.save(commit=False)
                franchise.client = user
                franchise.plan = plan
                franchise.save()
                domain = Domain(
                    domain=f"{franchise.schema_name}.{settings.DOMAIN}",
                    is_primary=True,
                    tenant=franchise,
                )
                domain.save()
                connection.set_tenant(franchise)
                User.initial_user(email=franchise.client.email, hash_password=franchise.client.password)
                connection.set_schema_to_public()
                messages.success(request, "La franquicia ha sido creada exitosamente")
                return redirect("franchise_list")
            except:
                messages.error(
                    request, "No se pudo registrar la franquicia, contacte al soporte"
                )
        else:
            messages.error(
                request, "No se pudo registrar la franquicia, contacte al soporte"
            )
    else:
        form_franchise = FranchiseForm()
        form_user = SignUpForm()

    return render(
        request,
        "franchises/registry_franchises.html",
        {
            "form_franchise": form_franchise,
            "form_user":form_user,
            "title": "Franchise registry",
            "domains": Domain.objects.exclude(tenant__schema_name="public")
            .select_related("tenant")
            .all(),
            "domain": settings.DOMAIN,
        },
    )


@auth_check_msg(users=(User.ADMINISTRATOR,))
def theme(request):
    instance = get_object_or_404(Franchise, name=request.tenant)
    connection.set_schema_to_public()
    form = ThemeForm(instance=instance)

    if request.method == "POST":
        form = ThemeForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            messages.success(request, "Se ha cambiado el tema")
            form = ThemeForm()
            return redirect("theme")
        else:
            messages.error(request, "Por favor revise los campos en rojo")

    return render(request, "franchises/franchise_theme.html", {"form": form})


@auth_check_msg(users=(User.ADMINISTRATOR, User.FRANCHISE))
def franchise_list(request):
    franchises = (
        Franchise.objects.filter(client=request.user)
        if request.user.user_type == User.FRANCHISE
        else Franchise.objects.all()
    )
    return render(
        request, "franchises/franchises_list.html", {"franchises": franchises}
    )


#@verify_position(allowed_positions=[User.FRANCHISE])
def dump_data(request, franchise_id=1):
    """
    Función que permite obtener un backup de los datos de la empresa a un cliente
    :param request:
    :param franchise_id:
    :return:
    """
    import sys
    from io import StringIO

    from django.http import HttpResponse
    from django.core.management import call_command
    from django.db import connection

    from franchises.models import Franchise

    franchise_backup = StringIO()

    try:
        franchise = Franchise.search(franchise_id)
        if franchise:
            connection.set_tenant(franchise)
            sysout = sys.stdout
            sys.stdout = franchise_backup
            call_command(
                "dumpdata","users", indent=4#, exclude=["auth", "sessions", "contenttypes"]
            )
            sys.stdout = sysout
            connection.set_schema_to_public()
        else:
            messages.error(
                request, "Error al generar el archivo, por favor intente nuevamente."
            )
            return redirect("franchise_list")

    except Exception:
        messages.error(
            request, "Error al generar el archivo, por favor intente nuevamente."
        )
        return redirect("franchise_list")

    franchise_backup.seek(0)
    response = HttpResponse(franchise_backup, content_type="application/text")
    franchise_backup.close()
    response["Content-Disposition"] = (
        "attachment; filename=backup-%s.json" % franchise.name
    )
    return response

franchises/templates/franchises/franchise_theme.html
{% extends "tables_base.html" %}
{% load bootstrap3 %}
{% load static %}

{% block title %}
  Cambiar tema
{% endblock %}

{% block page_title %}
  Cambiar Tema
{% endblock %}

{% block panel_title %}
  Cambiar tema
{% endblock %}

{% block breadcrumb %}
  <li class="active">Cambiar tema</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <div class="panel-control"></div>
          <h3 class="panel-title">Cambiar tema</h3>
        </div>
        <div class="panel-body">
          <form class="form-vertical" method="POST">{% csrf_token %}
            <div class="row">
              <div class="col-sm-12 col-md-12">
                {% bootstrap_form form layout="vertical" %}
                {% if form.errors %}
                  <div class="alert alert-danger">
                    {{ form.errors }}
                  </div>
                {% endif %}
              </div>
            </div>
            <div class="col-xs-12" align="right">
              <a href="{% url 'home' %}" class="btn btn-dark">Volver</a>
              <button type="submit" class="btn btn-primary">
                Guardar
              </button>
            </div>
          </form>
        </div>
        <div class="panel-footer"></div>
      </div>
    </div>
  </div>
{% endblock %}

franchises/templates/franchises/franchises_list.html
{% extends "tables_base.html" %}
{% load bootstrap3 %}
{% load static %}

{% block title %}
    Listado de franquicias
{% endblock %}

{% block page_title %}
    Listado de franquicias
{% endblock %}

{% block panel_title %}
    Listado de franquicias
{% endblock %}

{% block breadcrumb %}
    <li class="active">Listado de franquicias</li>
{% endblock %}

{% block content %}
    <div class="row">
        {#    <div class="col-sm-12 col-md-6 col-lg-4">#}
        {#      <div class="panel panel-primary">#}
        {#        <div class="panel-heading">#}
        {#          <div class="panel-control"></div>#}
        {#          <h3 class="panel-title">Gestionar franquicia</h3>#}
        {#        </div>#}
        {#        <div class="panel-body">#}
        {#          <form class="form-vertical" method="POST">{% csrf_token %}#}
        {#            <div class="row">#}
        {#              <div class="col-sm-12 col-md-12">#}
        {#                {% bootstrap_form form layout="vertical" %}#}
        {#                {% if form.errors %}#}
        {#                  <div class="alert alert-danger">#}
        {#                    {{ form.errors }}#}
        {#                  </div>#}
        {#                {% endif %}#}
        {#              </div>#}
        {#            </div>#}
        {#            <div class="col-xs-12" align="right">#}
        {#              <a href="{% url 'home' %}" class="btn btn-dark">Volver</a>#}
        {#              <button type="submit" class="btn btn-primary">#}
        {#                Guardar#}
        {#              </button>#}
        {#            </div>#}
        {#          </form>#}
        {#        </div>#}
        {#        <div class="panel-footer"></div>#}
        {#      </div>#}
        {#    </div>#}
        <div class="col-sm-12 col-md-6 col-lg-8">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-control">
                    </div>
                    <h3 class="panel-title">Franquicias registradas en el sistema</h3>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered responsive-table">
                            <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Nombre del esquema</th>
                                <th>Dominio(s)</th>
                                <th>Cliente</th>
                                <th>Plan</th>
                                <th>Fecha de vencimiento</th>
                                <th>Opciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for franchise in franchises %}
                                <tr>
                                    <td>{{ franchise.name }}</td>
                                    <td>{{ franchise.schema_name }}</td>
                                    <td>
                                        {% for domain in franchise.domains.all %}
                                            {{ domain }}<br>
                                        {% endfor %}

                                    </td>
                                    <td>{{ franchise.client|default_if_none:"" }}</td>
                                    <td>{{ franchise.plan|default_if_none:"" }}</td>
                                    <td>{{ franchise.validity }}</td>
                                    <td>
                                        <div class="dropdown">
                                            <button class="btn btn-sm btn-primary btn-active-primary dropdown-toggle"
                                                    data-toggle="dropdown" type="button">
                                                Opciones <i class="ti-angle-down"></i>
                                            </button>
                                            <ul class="dropdown-menu dropdown-menu-right">

                                                <li>
                                                    <a href="{% url 'franchise_backup_franchise' franchise.id %}">Descargar
                                                        copia de seguridad</a></li>
                                            </ul>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="panel-footer">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

franchises/templates/franchises/plan_management.html
{% extends "tables_base.html" %}
{% load bootstrap3 %}
{% load static %}

{% block title %}
  Gestionar planes
{% endblock %}

{% block page_title %}
  Gestionar planes
{% endblock %}

{% block panel_title %}
  Gestionar planes
{% endblock %}

{% block breadcrumb %}
  <li class="active">Gestionar planes</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-12 col-md-6 col-lg-4">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <div class="panel-control"></div>
          <h3 class="panel-title">Gestionar plan</h3>
        </div>
        <div class="panel-body">
          <form class="form-vertical" method="POST">{% csrf_token %}
            <div class="row">
              <div class="col-sm-12 col-md-12">
                {% bootstrap_form form layout="vertical" %}
                {% if form.errors %}
                  <div class="alert alert-danger">
                    {{ form.errors }}
                  </div>
                {% endif %}
              </div>
            </div>
            <div class="col-xs-12" align="right">
              <a href="{% url 'home' %}" class="btn btn-dark">Volver</a>
              <button type="submit" class="btn btn-primary">
                Guardar
              </button>
            </div>
          </form>
        </div>
        <div class="panel-footer"></div>
      </div>
    </div>
    <div class="col-sm-12 col-md-6 col-lg-8">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <div class="panel-control">
          </div>
          <h3 class="panel-title">Planes registrados en el sistema</h3>
        </div>
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table table-striped table-bordered responsive-table">
              <thead>
                <tr>
                  <th>Nombre</th>
                  <th>Descripción</th>
                  <th>Precio</th>
                  <th>Modulos</th>
                  <th>Máximo de usuarios</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
                {% for plan in plans %}
                  <tr>
                    <td>{{ plan.name }}</td>
                    <td>{{ plan.description }}</td>
                    <td>{{ plan.price }}</td>
                    <td>
                      {% for module in plan.get_avalaible_modules %}
                      <span class="label label-default">{{ module }}</span>
                      {% endfor %}
                    </td>
                    <td>{{ plan.max_users }}</td>
                    <td>
                      <div class="dropdown">
                        <button class="btn btn-sm btn-primary btn-active-primary dropdown-toggle"
                                data-toggle="dropdown" type="button">
                          Opciones <i class="ti-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-right">
                          <li>
                            <a href="{% url 'plan_management' plan.pk %}">Editar</a>
                          </li>
                        </ul>
                      </div>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <div class="panel-footer">
        </div>
      </div>
    </div>
  </div>
{% endblock %}

franchises/templates/franchises/registry_franchises.html
{% extends "landing_base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}
    Solicitar creación de empresa
{% endblock title %}

{% block page_title %}
    Solicitar creación de empresa
{% endblock page_title %}

{% block panel_title %}
    Solicitar creación de franquicia
{% endblock panel_title %}

{% block miga_pan %}
    <li class="active">Creación de franquicia</li>
{% endblock miga_pan %}

{% block content %}
    <div class="row">
        <div class="col-sm-4 col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-control"></div>
                    <h3 class="panel-title">Creación de franquicia</h3>
                </div>
                <div class="panel-body">

                    <form class="form-vertical" method="POST">{% csrf_token %}
                        {% bootstrap_form form_franchise layout="vertical" %}
                            <div class="panel-control">
                            <h3 class="panel-title">Administrador de la franquicia</h3>
                            </div>
                        {% bootstrap_form form_user layout="vertical" %}

                        <div class="col-sm-6 col-md-4">
                            {% if form_user.captcha.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert" style="margin-top:10px">
                                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span
                                            class="sr-only">Close</span></button>
                                    Debe realizar la verificación del reCAPTCHA ("No soy un robot")
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-xs-12" align="right">
                            <a href="{% url 'inicio' %}" class="btn btn-dark">Volver</a>

                            <button type="submit" class="btn btn-primary">
                                Guardar
                            </button>
                        </div>
                    </form>
                </div>
                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block  js %}
    {{ block.super }}
    <script>
        dominio = '{{ domain|safe }}';
        $id_schema_name = $('#id_schema_name');
        $help_text = $id_schema_name.next();
        if ($help_text.html() !== 'Esta será su direccion: midireccion.' + domain) {
            $help_text = $help_text.next();
        }

        $id_schema_name.on('change keydown paste input', function () {
            address = $id_schema_name.val();

            $help_text.html('Esta será su direccion: ' + address + domain);
        });
        $id_schema_name.trigger('change');

    </script>

    <script>
        static = {% static '' %};

        function get_theme_link() {
            return static + "css/themes/type-" + $("#id_theme").val() + "/theme-" + $("#id_colour").val() + ".min.css"
        }

        $('#id_theme, #id_colour').on('change', function () {
            $('#app-theme').attr("href", get_theme_link())
        })
    </script>

    <script src="{% static 'plugins/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js' %}"></script>
    <script>
        $('.component-date').datepicker({
            language: 'es',
            autoclose: true,
            format: 'yyyy-mm-dd',
            orientation: "bottom",
        });
    </script>
{% endblock %}